[package]
name = "glass-shard"
version = "0.1.0"
description.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
readme.workspace = true
publish.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[[bin]]
name = "glc"
path = "src/main.rs"

[dependencies]
glass-codegen = { workspace = true }

clap = { workspace = true }

color-eyre = { workspace = true }
thiserror = { workspace = true }